whitelist: false
no_whitelisted: '&aYou''re not that awesome to be whitelisted.'
whitelisted:
- Reinassance
- bradly378
- saikonohack
- saikono
- exren3588
- fine
- nounameee742
- flatron
- _mrsnup_
- luxio
- pyanyyvdupel
- npoctotun
- main_probrovova
- yanejorka01
- nightvizer
- matpehka
- 1darklight1
- gulgplayer
- runishyt
- Aleksejs
- goldendusst
- _magicshadow_
- itsfartunaru
- mrvoronyt
- costelemental
- baganutiy
- vam_pizda
- polovichok
- beesc9it
- dekoro9357
- ulucid0
- churochka
- laum_top
- 2b2tboy
- gorelkagames432
- julieonne
- raspingmango637
- flimeus_fresh
- lex
- neormon
- f2l1xon
- avikgold1
- kikorik777
- urdanton2203
- popyg
- megalolpro
- lightnight010
- eriloo
- reareddragon
- lolaol
- kollar_344
- nutulatut
- zaxar1000
- folkcartoon8283
- constellation__
- founder
- gleiz_saltum
- corwin4_
- neforidze
- de1ka1337
- notch_
- notch
- builder_russia
- re1dertwo
- mortobello
- xelak
- isamuraii
- linch_56
- deripaska72
- motypissy666
- bradly368
- shrekotan
- dalphi3674
- parmisha1305
- wh1tewin
- ra1de7
- paxanhik123
- npoctotun1
- ochkobyba
- vitya922
- artempe3273
- bennefitik
- nappywnteab52
- napywnteab52
- emerald_tatum
- iammarty409
- keshok_yt
- qedr
- valhemir
- mae110
